version: "3.12"

services:
  web:
    build:
      context: .
    container_name: fastapi_app
    working_dir: /TZProject
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    env_file:
      - .env.examole
    ports:
      - "8000:8000"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    image: postgres:15-alpine
    container_name: postgres_tz
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
